[
  # `lib/protocol/` is generated by `mix typedb.grpc.gen` from TypeDB's own
  # `.proto` files. Formatting it would create churn on every regeneration and
  # would make a diff between two protocol versions unreadable, which is the one
  # diff anybody ever reads there.
  inputs: [
    "{mix,.formatter}.exs",
    "lib/typedb/**/*.{ex,exs}",
    "lib/mix/**/*.{ex,exs}",
    "test/**/*.{ex,exs}"
  ],
  line_length: 110
]
